mongo:
  repository: mongo
  tag: 5.0.9
  replicas: 1
  memorylimit: "8Gi"
  cpulimit: "500m"
  memoryrequest: "8Gi"
  cpurequest: "500m"
  pvcbacking: "argo-mongo"
redis:
  repository: argovis/redis
  tag: 7.0.3-220713
  replicas: 1
  memory: "100Mi"
  cpu: "50m"
api:
  repository: argovis/api
  tag: dev
  replicas: 4
  memory: "1000Mi"
  cpu: "500m"
  argocore: 'here'
apix:
  repository: argovis/api
  tag: dev
  replicas: 0
  memory: "1500Mi"
  cpu: "500m"
keymanager:
  repository: argovis/api-keymanager
  tag: 2.0.0
  replicas: 1
  memory: "100Mi"
  cpu: "100m"

