mongo:
  repository: mongo
  tag: 4.2.3
  replicas: 1
  memory: "8Gi"
  cpu: "500m"
redis:
  repository: argovis/redis
  tag: 6.2.6-211114
  replicas: 1
  memory: "500Mi"
  cpu: "100m"
api:
  repository: argovis/api
  tag: 2.0.0-rc7
  replicas: 2
  memory: "2Gi"
  cpu: "1000m"
ng:
  repository: argovis/ng
  tag: 2.0.0-rc5
  replicas: 1
  api_root: http://argovis-api-atoc-argovis-dev.apps.containers01.colorado.edu
  dp_root: http://argovis-datapages-atoc-argovis-dev.apps.containers01.colorado.edu
  memory: "1Gi"
  cpu: "250m"
datapages:
  repository: argovis/datapages
  tag: 2.0.0-rc2
  replicas: 1
  memory: "500Mi"
  cpu: "250m"
