apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongo-ingress
spec:
  podSelector:
    matchLabels:
      component: mongo
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: api
    ports:
      - port: 27017
