apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: atoc-argovis-drifters-prod
  name: prometheus-scrape
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services"]
    verbs: ["get", "list", "watch"]
