apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: atoc-argovis-drifters-prod
  name: prometheus-scrape-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-scrape
subjects:
  - kind: ServiceAccount
    name: default
    namespace: atoc-argovis-drifters-prod
