apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      name: argoredis
      labels:
        component: redis
        tier: db
    spec:
      containers:
        - name: argoredis
          image: "{{ .Values.redis.repository }}:{{ .Values.redis.tag }}"
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
            limits:
              memory: {{ .Values.redis.memory }}
              cpu: {{ .Values.redis.cpu }}
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
