mongo:
  repository: mongo
  tag: 5.0.27
  replicas: 1
  memorylimit: "8Gi"
  cpulimit: "1000m"
  memoryrequest: "8Gi"
  cpurequest: "1000m"
  pvcbacking: "mongo-back"
redis:
  repository: argovis/redis
  tag: 7.0.15-240702
  replicas: 1
  memory: "100Mi"
  cpu: "50m"
api:
  repository: argovis/api
  tag: 2.29.3
  replicas: 1
  memory: "900Mi"
  cpu: "400m"
  argocore: 'https://argovis-api.colorado.edu'
  argonode: 'miami'
prom:
  repository: argovis/prometheus
  tag: 240917
  replicas: 1
  memory: "100Mi"
  cpu: "100m"
  pvcbacking: prometheus-tsdb
