apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: argoapi
      labels:
        app: api
    spec:
      containers:
        - name: argoapi
          image: "{{ .Values.api.repository }}:{{ .Values.api.tag }}"
          imagePullPolicy: Always
          env:
          - name: NODE_OPTIONS
            value: --max_old_space_size=2048
          resources:
            requests:
              memory: "0Gi"
              cpu: "0m"
            limits:
              memory: {{ .Values.api.memory }}
              cpu: {{ .Values.api.cpu }}

