apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapages-deployment
  labels:
    app: datapages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datapages
  template:
    metadata:
      name: argodatapages
      labels:
        app: datapages
    spec:
      containers:
        - name: argodatapages
          image: "{{ .Values.datapages.repository }}:{{ .Values.datapages.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "0Gi"
              cpu: "0m"
            limits:
              memory: "500Mi"
              cpu: "250m"
