apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapages-deployment
  labels:
    app: datapages
spec:
  replicas: {{ .Values.datapages.replicas }}
  selector:
    matchLabels:
      app: datapages
  template:
    metadata:
      name: argodatapages
      labels:
        app: datapages
    spec:
      containers:
        - name: argodatapages
          image: "{{ .Values.datapages.repository }}:{{ .Values.datapages.tag }}"
          imagePullPolicy: Always
          env:
          - name: ARGOVIS_API_KEY
            valueFrom:
              secretKeyRef:
                name: apitoken
                key: token
          resources:
            requests:
              memory: "0Gi"
              cpu: "0m"
            limits:
              memory: {{ .Values.datapages.memory }}
              cpu: {{ .Values.datapages.cpu }}
