apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-deployment
  labels:
    app: ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng
  template:
    metadata:
      name: argong
      labels:
        app: ng
    spec:
      containers:
        - name: argong
          image: "{{ .Values.ng.repository }}:{{ .Values.ng.tag }}"
          imagePullPolicy: Always
          env:
          - name: ARGOVIS_API_ROOT
            value: {{ .Values.ng.api_root }}
          - name: ARGOVIS_DP_ROOT
            value: {{ .Values.ng.dp_root }}
          resources:
            requests:
              memory: "0Gi"
              cpu: "0m"
            limits:
              memory: "1Gi"
              cpu: "250m"
      securityContext:
        runAsUser: 1000830000
        runAsGroup: 1000830000
