apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-deployment
spec:
  replicas: {{ .Values.ng.replicas }}
  selector:
    matchLabels:
      component: ng
  template:
    metadata:
      name: argong
      labels:
        component: ng
        tier: web
    spec:
      containers:
        - name: argong
          image: "{{ .Values.ng.repository }}:{{ .Values.ng.tag }}"
          imagePullPolicy: Always
          env:
          - name: ARGOVIS_API_ROOT
            value: {{ .Values.ng.api_root }}
          - name: ARGOVIS_DP_ROOT
            value: {{ .Values.ng.dp_root }}
          - name: ARGOVIS_API_KEY
            valueFrom:
              secretKeyRef:
                name: apitoken
                key: token
          resources:
            requests:
              memory: "0Gi"
              cpu: "0m"
            limits:
              memory: {{ .Values.ng.memory }}
              cpu: {{ .Values.ng.cpu }}
      securityContext:
        runAsUser: 1000660000
        runAsGroup: 1000660000
