apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-ingress
spec:
  podSelector:
    matchLabels:
      component: redis
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: api
    ports:
      - port: 6379
